// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_training/test/notifier/weather_forecast_view_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_training/view/weather/weather_forecast_view_state.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:yumemi_weather/yumemi_weather.dart' as _i2;

import 'weather_forecast_view_state_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [YumemiWeather].
///
/// See the documentation for Mockito's code generation for more information.
class MockYumemiWeather extends _i1.Mock implements _i2.YumemiWeather {
  @override
  String fetchSimpleWeather() => (super.noSuchMethod(
        Invocation.method(
          #fetchSimpleWeather,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchSimpleWeather,
            [],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchSimpleWeather,
            [],
          ),
        ),
      ) as String);

  @override
  String fetchThrowsWeather(String? area) => (super.noSuchMethod(
        Invocation.method(
          #fetchThrowsWeather,
          [area],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchThrowsWeather,
            [area],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchThrowsWeather,
            [area],
          ),
        ),
      ) as String);

  @override
  String fetchWeather(String? jsonString) => (super.noSuchMethod(
        Invocation.method(
          #fetchWeather,
          [jsonString],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchWeather,
            [jsonString],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #fetchWeather,
            [jsonString],
          ),
        ),
      ) as String);

  @override
  String syncFetchWeather(String? jsonString) => (super.noSuchMethod(
        Invocation.method(
          #syncFetchWeather,
          [jsonString],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #syncFetchWeather,
            [jsonString],
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #syncFetchWeather,
            [jsonString],
          ),
        ),
      ) as String);
}

/// A class which mocks [Listener].
///
/// See the documentation for Mockito's code generation for more information.
class MockListener extends _i1.Mock implements _i4.Listener {
  @override
  void call(
    _i5.WeatherForecastViewState? previous,
    _i5.WeatherForecastViewState? next,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #call,
          [
            previous,
            next,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
